name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: Install Qt and MinGW
        run: |
          aqt install-qt windows desktop 6.10.2 win64_mingw -O C:\Qt
          aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw1310 -O C:\Qt
          $qtPath = "C:\Qt\6.10.2\mingw_64"
          $qtPathForward = $qtPath -replace "\\", "/"
          echo "Qt6_DIR=$qtPathForward" >> $env:GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$qtPathForward" >> $env:GITHUB_ENV
          "C:\Qt\6.10.2\mingw_64\bin" >> $env:GITHUB_PATH
          "C:\Qt\Tools\mingw1310_64\bin" >> $env:GITHUB_PATH

      - name: install UPX
        run: | 
               iwr -Uri "https://github.com/upx/upx/releases/download/v5.1.1/upx-5.1.1-win64.zip" -OutFile upx.zip
               expand-archive -Path upx.zip -DestinationPath upx -Force
               $upxDir = Get-ChildItem -Path upx -Directory | Select-Object -First 1
               $upxPath = $upxDir.FullName
               echo "UPX_PATH=$upxPath" >> $env:GITHUB_ENV
               echo "$upxPath" >> $env:GITHUB_PATH
      
      - name: Verify UPX installation
        run: |
               upx --version
      
      - name: Build
        run: |
               mkdir build
               cd build
               cmake .. -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" -DUPX_EXECUTABLE="${{ env.UPX_PATH }}\upx.exe"
               cmake --build .

      - name: Package and Clean
        shell: cmd
        run: |
            cd build
            for /d %%i in (*) do (
                if not "%%i" == "JiyuUdpAttack" if not "%%i" == "MemoryErasure" (
                    rd /s /q "%%i"
                )
            )
            cd JiyuUdpAttack
            if exist CMakeFiles rd /s /q CMakeFiles
            if exist juyuudpattack_autogen rd /s /q juyuudpattack_autogen
            if exist cmake_install.cmake del cmake_install.cmake
            cd ..
            mkdir jiyukiller-package
            copy "MemoryErasure\MemoryErasure.exe" "jiyukiller-package\"
            xcopy "JiyuUdpAttack" "jiyukiller-package\JiyuUdpAttack" /s /e /i
            powershell Compress-Archive -Path jiyukiller-package -DestinationPath jiyukiller.zip               

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_id }}
          name: Release v${{ github.run_id }}
          draft: false
          prerelease: false
          files: ./build/jiyukiller.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
